export const Lang = {
  en: {
    FEELTHEFLOW: "FEEL THE FLOW",
    heroSubTitle: "Next-Generation Streaming Application",
    heroText:
      "Redefining simplicity with a clean and seamless experience that works with complete efficiency. No clutter. No distractions. Just smart, fast performance powered by AI.",
    ManagePlaylistTitle: "Manage Playlist",
    LoginPlaylist: "Login to add your playlist",
    Login: "Login",
    home: "Home",
    WhoWeAre: "Who We Are",
    vision: "Vision",
    features: "Features",
    howitworks: "How It Works",
    contact: "Contact",
    reseller:"Reseller",
    WishTvWebsite:
      "Our platform is the hub for entertainment solutions, boasting an extensive collection of streaming technologies and thoughtfully curated content.",
    WishTvDevice: "Watch Nova TV with these compatible streaming devices",
    ActivateDeviceOne: "Activate Devices",
    SwitchMac: "Switch Mac",
    ParentPin: "Parent Pin",
    AccountDetails: "Account Details",
    Logout: "Logout",
    WishTvAboutOne:
      "Nova TV is the most advanced and user-friendly TV media player.",
    WishTvAboutTwo:
      "With Nova TV, you will enjoy your favorite media on your smart TV.",
    MobileVersion: "Mobile version of",
    Available: "is available",
    wishtvAppAboutThree:
      "Available for Android on Play Store and iOS on App Store.",
    FAQsTitle: "Frequently Asked Questions",
    answerOne: "Does Nova TV contain any channels? Where can I get a playlist?",
    questionOne:
      "No, Nova TV application does not include any channels and no information will be provided about where you can get channels or channel packages. Also, application developers are not responsible for the content uploaded to Wish TV.",
    answerTwo: "How can I become a certified Wish TV provider?",
    questionTwo:
      "You can apply on the Wish TV platform or contact the support team for more information on becoming a certified provider.",
    answerThree: "How can I become a certified Wish TV provider?",
    questionThree:
      "If you experience a loading screen that never finishes, please restart the app or check your internet connection.",
    answerFour: "How can I use Nova TV?",
    questionFour:
      "Nova TV is simple to use. Download the app, log in with your credentials, and start enjoying your favorite media.",
    answerFive: "Having trouble finding our app in stores?",
    questionFive:
      "If you're having trouble finding our app, please ensure you're searching in the correct store for your device's OS (Android or iOS).",
    answerSix:
      "My MAC address has changed after I switched to another connection type.",
    questionSix:
      "If your MAC address changed after switching connection types, you might need to contact support for assistance in updating your credentials.",
    SendMessage: "Send Us a Message",
    ContactUs: "Contact Us",
    FullName: "Full Name",
    Email: "Email",
    Subject: "Subject",
    YourMessage: "Type Your message...",
    SendMessageButton: "Send Message",
    About: "About",
    aboutDesc:
      "Nova TV is an Player app that allows you to watch high-quality content on all devices, whether it's your TV, mobile, or Android box, regardless of your internet speed",
    PoliciesConditions: "Policies & Conditions",
    TermsConditions: "Terms & Conditions",
    PrivacyPolicy: "Privacy Policy",
    footer: "Copyright © 2025 Nova TV",
    AddPlaylist: "Add Playlist",
    LoadingPlaylists: "Loading playlists...",
    Playlist: "Playlist",
    Actions: "Actions",
    ActivateDevice: "Activate Device",
    Price: "Price",
    PaymentMethod: "Payment method",
    noteOne: "NOTE",
    noteDesc:
      "Nova TV does not provide content and is purely a media player. To use Wish TV, you must upload your own playlist. If you don’t have a playlist, you cannot use the Wish Player. In this case, do not pay. Also, we do not allow activation for users who do not have a playlist.",
    SwitchDevice: "Switch Device MAC",
    MaxLength: "Max length",
    newMacAddress: "New MAC Address",
    transferMacAddress:
      "Transfer your activation and playlists to another device MAC Address",
    noteTwo: "NOTE",
    noteDescTwo:
      "Your device login information, playlists, and activation period shall be transferred to this new device MAC address. Your old MAC address device will no longer be attached to this account.",
    Save: "Save",
    parentPinTitle: "Parent Pin",
    resetParentPIN: "Reset Parent PIN",
    newParentPin: "New Parent Pin",
    noteThree: "NOTE",
    noteDescThree:
      "If you forgot your parent pin in the app, you can change the parent pin here.",
    AccountDetailsTitle: "Account Details",
    Status: "Status",
    CreationDate: "Creation Date",
    ExpirationDate: "Expiration Date",
    AddPlaylistTitle: "Add Playlist",
    EditPlaylistTitle: "Edit Playlist",
    PlaylistName: "Playlist Name",
    EnterPlaylistName: "Enter Playlist Name",
    PlaylistURL: "Playlist URL",
    EnterPlaylistURL: "Enter Playlist URL",
    ProtectedPlaylist: "Protected Playlist",
    noteFour: "NOTE",
    noteDescFour:
      "Protected playlists will not be viewed or modified without entering a PIN.",
    Password: "Password",
    EnterPassword: "Enter Password",
    Cancel: "Cancel",
    Saving: "Saving...",
    UpdatePlaylist: "Update Playlist",
    ErrorMessageOne: "An error occurred",
    ErrorMessageTwo: "Playlist URL is required",
    ErrorMessageThree: "Password is required for protected playlists",
    EditErrorMessageOne: "Failed to update playlist",
    EditErrorMessageTwo: "Error updating playlist",
    EditErrorMessageThree: "An error occurred while updating the playlist",
    SaveChanges: "Save Changes",
    AccountDetailstTitle: "Account Details",
    AddPlaylistOne: "Add Playlist",
    AddPlaylistTwo: "Add Playlist",
    Enterplaylistname: "Enter playlist Name",
    EnterplaylistURL: "Enter Playlist URL",
    Enterpassword: "Enter password",
    EditPlaylist: "Edit Playlist",
    PlaylistNameOne: "Playlist Name",
    PlaylistURLOne: "Playlist URL",
    PasswordOne: "Password",
    EnterpasswordOne: "Enter password",
    wishtvAboutone:
      "Nova TV is the most advanced and user-friendly TV media player.",
    wishtvAboutTwo:
      "With Nova TV, you will enjoy your favorite media on your smart TV.",
    // Footer translations
    footerDescription:
      "Next-generation streaming application redefining simplicity.",
    quickLinks: "Quick Links",
    whoWeAre: "Who We Are",
    features: "Features",
    howItWorks: "How It Works",
    becomeReseller: "Become a Reseller",
    support: "Support",
    contactUs: "Contact Us",
    manageDevices: "Manage Devices",
    faq: "FAQ",
    documentation: "Documentation",
    legal: "Legal",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    cookiePolicy: "Cookie Policy",
    copyright: "© 2024 Intertament. All rights reserved.",
    poweredBy: "Powered by Servo IT",
    // WhatsApp and Login form translations
    whatsappAccountName: "Servo Player",
    whatsappStatusMessage: "Typically replies within 1 hour",
    whatsappChatMessage: "Hello! How can we help you?",
    whatsappPlaceholder: "Contact us",
    loginDescription: "Enter your MAC Address & Device Key to continue",
    macAddressLabel: "MAC Address",
    macAddressPlaceholder: "Enter your MAC Address",
    deviceKeyLabel: "Device Key",
    deviceKeyPlaceholder: "Enter your Device Key",
    loginInfoText:
      "Your MAC Address and Device Key can be found in your app settings. If you need help, please contact support.",
    loginFailedMessage: "Login failed. Please try again.",
    // WhoWeAre component translations
    whoWeAreTitle: "Who We Are",
    whoWeAreText1: "We are",
    whoWeAreText2: "Intertament",
    whoWeAreText3:
      ", a company that offers a next-generation streaming application redefining simplicity.",
    whoWeAreText4:
      "Our platform focuses on what truly matters — a clean and seamless experience that works with complete efficiency.",
    whoWeAreText5: "No clutter. No distractions.",
    whoWeAreText6:
      "Just smart, fast performance powered by AI, along with business support and development tools for resellers and industry professionals.",
    // Vision component translations
    visionTitle: "Our Vision",
    visionText: "To become the most",
    visionTrusted: "trusted",
    visionUserFriendly: "user-friendly",
    visionFutureReady: "and future-ready",
    visionTextEnd: "platform in the world.",
    visionTrustedLabel: "Trusted",
    visionUserFriendlyLabel: "User-Friendly",
    visionFutureReadyLabel: "Future-Ready",
    // Mission component translations
    missionTitle: "Our Mission",
    missionText1: "To provide users with a",
    missionText1Highlight: "fluid, seamless, and innovative",
    missionText1End: "streaming experience",
    missionText2: "To offer resellers an",
    missionText2Highlight: "efficient management platform",
    missionText2End: "and growth support",
    // Values component translations
    valuesTitle: "Our Values",
    valuesSubtitle: "The principles that guide everything we do",
    valuesSimplicity: "Simplicity",
    valuesSimplicityDesc: "Clean, intuitive design that anyone can use",
    valuesTrust: "Trust",
    valuesTrustDesc: "Reliable and secure platform you can depend on",
    valuesInnovation: "Innovation",
    valuesInnovationDesc: "Cutting-edge AI technology for the future",
    valuesComfort: "Comfort",
    valuesComfortDesc: "Seamless experience designed for your ease",
    valuesTransparency: "Transparency",
    valuesTransparencyDesc: "Open and honest in everything we do",
    valuesSupport: "Support",
    valuesSupportDesc: "24/7 assistance whenever you need us",
    // Features component translations
    featuresTitle: "Player Features",
    featuresSubtitle:
      "Everything you need for the perfect streaming experience",
    featuresModernDesign: "Modern & Clean Design",
    featuresModernDesignDesc:
      "A lightweight, eye-friendly interface that puts content first",
    featuresInstantAccess: "Instant Access",
    featuresInstantAccessDesc:
      "Enter the server and start watching immediately",
    featuresSecureStable: "Secure & Stable",
    featuresSecureStableDesc:
      "Built for maximum performance, protection, and speed",
    featuresInteractiveIntelligence: "Interactive Intelligence",
    featuresInteractiveIntelligenceDesc:
      "Learns from your usage to recommend the best AI-powered content",
    featuresSmartSearch: "Smart Search Engine",
    featuresSmartSearchDesc:
      "Fast, intuitive, and intelligent content discovery",
    // HowItWorks component translations
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Get started in just 3 simple steps",
    howItWorksStep1Title: "Download & Install",
    howItWorksStep1Desc:
      "Search for Servo Player on your device's store and install it.",
    howItWorksStep1Note: "Currently available on Samsung and LG",
    howItWorksStep1ComingSoon:
      "Coming soon to Android TV, iOS, Toku, Windows, and Apple TV",
    howItWorksStep2Title: "Enter Your Credentials",
    howItWorksStep2Desc:
      "Enter your server URL or activation code via the website.",
    howItWorksStep3Title: "Enjoy Streaming",
    howItWorksStep3Desc:
      "Let our AI enhance your experience and enjoy smooth streaming.",
    howItWorksAvailablePlatforms: "Available Platforms",
    howItWorksComingSoon: "Coming Soon",
    // WhyChooseUs component translations
    whyChooseUsTitle: "Why Choose to Become a Reseller With Us",
    whyChooseUsSubtitle:
      "Partner with Servo today and Enjoy the streaming experience of the future",
    whyChooseUsFullControl: "Full Control",
    whyChooseUsFullControlDesc:
      "Full Control over your clients through a professional dashboard",
    whyChooseUsSupport: "24/7 Technical Support",
    whyChooseUsSupportDesc: "Round-the-clock assistance whenever you need it",
    whyChooseUsPricing: "Competitive Pricing",
    whyChooseUsPricingDesc: "Excellent value for money with wholesale rates",
    whyChooseUsOffers: "Exclusive Offers",
    whyChooseUsOffersDesc: "Special packages and deals for our resellers",
    whyChooseUsTrusted: "Trusted Platform",
    whyChooseUsTrustedDesc:
      "A Trusted, Modern Platform Powered by AI — Loved by customers",
    whyChooseUsManagement: "Centralized Management",
    whyChooseUsManagementDesc:
      "Control all users, devices, and subscriptions in one place",
    whyChooseUsPerformance: "Reliable Performance",
    whyChooseUsPerformanceDesc:
      "Say goodbye to downtime and instability — Servo delivers consistent, smooth performance 24/7",
    whyChooseUsPartnership:
      "👉 Partner with Servo today and give your customers the streaming experience of the future.",
    whyChooseUsStartPartnership: "Start Your Partnership",
    // Contact component translations
    contactTitle: "Contact Us",
    contactSubtitle:
      "For more information or business inquiries, please don't hesitate to reach out",
    contactGetInTouch: "Get in Touch",
    contactEmail: "Email",
    contactSupport: "Support",
    contactSupportAvailable: "24/7 Available",
    contactResponseTime: "Response Time",
    contactResponseTimeValue: "Within 24 hours",
    contactFollowUs: "Follow Us",
    contactName: "Name",
    contactNamePlaceholder: "Your name",
    contactEmailPlaceholder: "your@email.com",
    contactSubject: "Subject",
    contactSubjectPlaceholder: "How can we help?",
    contactMessage: "Message",
    contactMessagePlaceholder: "Your message...",
    contactSendMessage: "Send Message",
  },
  ar: {
    FEELTHEFLOW: "أشعُر بالحركة",
    LoginPlaylist: "قم بتسجيل الدخول لإضافة قائمة التشغيل الخاصة بك",
    Login: "تسجيل الدخول",
    heroSubTitle: "تطبيق بث من الجيل القادم",
    heroText:
      "نعيد تعريف البساطة من خلال تجربة نظيفة وسلسة تعمل بكفاءة تامة. بدون فوضى، بدون تشتيت. فقط أداء ذكي وسريع مدعوم بالذكاء الاصطناعي.",
    home: "الرئيسية",
    WhoWeAre: "من نحن",
    vision: "الرؤية",
    features: "المميزات",
    howitworks: "كيف يعمل",
    reseller:"بائع",
    contact: "تواصل معنا",
    WishTvWebsite:
      "منصتنا هي المركز لحلول الترفيه، وتتميز بمجموعة واسعة من تقنيات البث والمحتوى المختار بعناية.",
    WishTvDevice: "شاهد خدمات تطبيقنا باستخدام اجهزة البث المتوافقه",
    ManagePlaylistTitle: "إدارة قائمة التشغيل",
    ActivateDeviceOne: "تفعيل الأجهزة",
    SwitchMac: "تبديل الماك",
    ParentPin: "رمز التحكم العائلى",
    AccountDetails: "تفاصيل الحساب",
    Logout: "تسجيل الخروج",
    wishtvAboutone:
      "تطبيقنا هو مشغل الوسائط التلفزيونية الأكثر تقدمًا وسهولة في الاستخدام.",
    wishtvAboutTwo:
      "مع تطبيقنا، سوف تستمتع بالوسائط المفضلة لديك على التلفزيون الذكي الخاص بك.",
    MobileVersion: "النسخة المحمولة من",
    available: "متاحه",
    wishtvAppAboutThree:
      "متاح لنظام الاندرويد على بلاى ستور ولاجهزة الايفون على اب ستور",
    faqsTitle: "الأسئلة الشائعة",
    answerOne:
      "هل يحتوي تطبيقنا على أي قنوات؟ أين يمكنني الحصول على قائمة تشغيل؟",
    questionOne:
      "لا، لا يتضمن تطبيقنا أي قنوات ولن يتم تقديم أي معلومات حول المكان الذي يمكنك الحصول فيه على القنوات أو باقات القنوات. كما أن مطوري التطبيق غير مسؤولين عن المحتوى الذي يتم تحميله على Wish TV.",
    answerTwo: "كيف يمكنني أن أصبح مقدم خدمة ويش تى فى معتمدًا؟",
    questionTwo:
      "يمكنك التقديم على منصة ويش تى فى أو التواصل مع فريق الدعم للحصول على مزيد من المعلومات حول كيفية أن تصبح مقدم خدمة معتمدًا.",
    answerThree: "هل لديك شاشة تحميل لا تنتهي؟",
    questionThree:
      "إذا واجهت شاشة تحميل لا تنتهي أبدًا، فيرجى إعادة تشغيل التطبيق أو التحقق من اتصالك بالإنترنت.",
    answerFour: "كيف يمكنني استخدام نوفا تى فى؟",
    questionFour:
      "يعد استخدام تطبيقنا سهلاً. قم بتنزيل التطبيق، وسجّل الدخول باستخدام بيانات الاعتماد الخاصة بك، وابدأ في الاستمتاع بالوسائط المفضلة لديك.",
    answerFive: "هل تواجه مشكلة في العثور على تطبيقنا في المتاجر؟",
    questionFive:
      "إذا كنت تواجه مشكلة في العثور على تطبيقنا، فيرجى التأكد من أنك تبحث في المتجر الصحيح لنظام التشغيل الخاص بجهازك (اندرويد أو ايفون).",
    answerSix:
      "لقد تغير عنوان ماك الخاص بي بعد أن قمت بالتبديل إلى نوع اتصال آخر.",
    questionSix:
      "إذا تغير عنوان ماك الخاص بك بعد تبديل أنواع الاتصال، فقد تحتاج إلى الاتصال بالدعم للحصول على المساعدة في تحديث بيانات الاعتماد الخاصة بك.",
    SendMessage: "أرسل لنا رسالة",
    ContactUs: "تواصل معنا",
    FullName: "الاسم بالكامل",
    Email: "البريد الالكترونى",
    Subject: "الموضوع",
    YourMessage: "اكتب رسالتك هنا",
    SendMessageButton: "ارسل رسالة",
    About: "من نحن",
    aboutDesc:
      "Nova TV هو تطبيق مشغل يسمح لك بمشاهدة محتوى عالي الجودة على جميع الأجهزة، سواء كان جهاز التلفزيون أو الهاتف المحمول أو جهاز Android، بغض النظر عن سرعة الإنترنت لديك`",
    PoliciesConditions: "السياسات والشروط",
    TermsConditions: "الشروط والأحكام",
    PrivacyPolicy: "سياسة الخصوصية",
    footer: "جميع الحقوق محفوظة © 2025 قناة نوفا تي في",
    AddPlaylist: "إضافة قائمة التشغيل",
    LoadingPlaylists: "جاري تحميل قوائم التشغيل...",
    Playlist: "قائمة التشغيل",
    Actions: "الإجراءات",
    ActivateDevice: "تفعيل الجهاز",
    Price: "السعر",
    PaymentMethod: "طريقة الدفع",
    noteOne: "ملحوظة",
    noteDesc:
      "لا يوفر تطبيقنا أي محتوى، وهو عبارة عن مشغل وسائط فقط. لاستخدام تطبيقنا، يتعين عليك تحميل قائمة التشغيل الخاصة بك. إذا لم يكن لديك قائمة تشغيل، فلن تتمكن من استخدام مشغل ويش بعد الآن، لذا في هذه الحالة لا تدفع. كما أننا لا نسمح بالتنشيط للمستخدمين الذين ليس لديهم قوائم تشغيل.",
    SwitchDevice: "تبديل جهاز MAC",
    MaxLength: "الحد الاقصى",
    newMacAddress: "عنوان MAC الجديد",
    transferMacAddress: "نقل التنشيط وقوائم التشغيل إلى عنوان MAC لجهاز آخر",
    noteTwo: "ملحوظة",
    noteDescTwo:
      "سيتم نقل معلومات تسجيل الدخول الخاصة بجهازك وقوائم التشغيل وفترة التنشيط إلى عنوان MAC الجديد الخاص بهذا الجهاز. لن يكون عنوان MAC القديم الخاص بك مرتبطًا بهذا الحساب بعد الآن.",
    Save: "حفظ",
    parentPinTitle: "رمز التحكم العائلى",
    resetParentPIN: "إعادة تعيين رقم التعريف الشخصي للوالدين",
    newParentPin: "رمز الجديد التحكم العائلى",
    noteThree: "ملحوظة",
    noteDescThree:
      "إذا نسيت رمز التعريف الشخصي الأساسي الخاص بك في التطبيق، فيمكنك تغيير رمز التعريف الشخصي الأساسي هنا.",
    AccountDetailsTitle: "تفاصيل الحساب",
    Status: "حالة",
    CreationDate: "تاريخ الأنشاء",
    ExpirationDate: "تاريخ الأنتهاء",
    AddPlaylistOne: "إضافة قائمة التشغيل",
    AddPlaylistTwo: "إضافة قائمة التشغيل",
    EditPlaylistOne: "تعديل قائمة التشغيل",
    PlaylistName: "اسم قائمة التشغيل",
    EnterPlaylistName: "أدخل اسم قائمة التشغيل",
    PlaylistURL: "رابط قائمة التشغيل",
    EnterPlaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    ProtectedPlaylist: "قائمة التشغيل المحمية",
    noteFour: "ملحوظة",
    noteDescFour:
      "لن يتم عرض قوائم التشغيل المحمية أو تعديلها دون إدخال رقم التعريف الشخصي (PIN)",
    Password: "كلمة المرور",
    EnterPassword: "ادخل كلمة المرور",
    Cancel: "إلغاء",
    Saving: "جارى التعديل...",
    UpdatePlaylist: "تحديث قائمة التشغيل",
    errorMessageOne: "اسم قائمة التشغيل مطلوب",
    errorMessageTwo: "مطلوب عنوان URL لقائمة التشغيل",
    errorMessageThree: "مطلوب كلمة مرور لقوائم التشغيل المحمية",
    EditErrorMessageOne: "فشل في تحديث قائمة التشغيل",
    EditErrorMessageTwo: "خطأ في تحديث قائمة التشغيل:",
    EditErrorMessageThree: "حدث خطأ أثناء تحديث قائمة التشغيل",
    EditPlaylist: "تعديل قائمة التشغيل",
    PlaylistNameOne: "اسم قائمة التشغيل",
    PlaylistURLOne: "رابط قائمة التشغيل",
    PasswordOne: "كلمة المرور",
    EnterPasswordOne: "ادخل كلمة المرور",
    SaveChanges: "حفظ التغيرات",
    AccountDetailstTitle: "تفاصيل الحساب",
    Enterplaylistname: "أدخل اسم قائمة التشغيل",
    EnterplaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    Enterpassword: "ادخل كلمة المرور",
    // Footer translations
    footerDescription: "تطبيق البث من الجيل التالي يعيد تعريف البساطة.",
    quickLinks: "روابط سريعة",
    whoWeAre: "من نحن",
    features: "الميزات",
    howItWorks: "كيف يعمل",
    becomeReseller: "كن موزعًا",
    support: "الدعم",
    contactUs: "تواصل معنا",
    manageDevices: "إدارة الأجهزة",
    faq: "الأسئلة الشائعة",
    documentation: "الوثائق",
    legal: "قانوني",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    cookiePolicy: "سياسة ملفات تعريف الارتباط",
    copyright: "© 2024 إنترتامنت. جميع الحقوق محفوظة.",
    poweredBy: "مدعوم من Servo IT",
    // WhatsApp and Login form translations
    whatsappAccountName: "سيرفو بلاير",
    whatsappStatusMessage: "عادة ما يرد خلال ساعة واحدة",
    whatsappChatMessage: "مرحباً! كيف يمكننا مساعدتك؟",
    whatsappPlaceholder: "تواصل معنا",
    loginDescription: "أدخل عنوان MAC ومفتاح الجهاز للمتابعة",
    macAddressLabel: "عنوان MAC",
    macAddressPlaceholder: "أدخل عنوان MAC الخاص بك",
    deviceKeyLabel: "مفتاح الجهاز",
    deviceKeyPlaceholder: "أدخل مفتاح الجهاز",
    loginInfoText:
      "يمكن العثور على عنوان MAC ومفتاح الجهاز في إعدادات التطبيق. إذا كنت بحاجة إلى مساعدة، يرجى الاتصال بالدعم.",
    loginFailedMessage: "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    // WhoWeAre component translations
    whoWeAreTitle: "من نحن",
    whoWeAreText1: "نحن",
    whoWeAreText2: "إنترتامنت",
    whoWeAreText3: "، شركة تقدم تطبيق بث من الجيل التالي يعيد تعريف البساطة.",
    whoWeAreText4:
      "تركز منصتنا على ما يهم حقاً — تجربة نظيفة وسلسة تعمل بكفاءة كاملة.",
    whoWeAreText5: "لا فوضى. لا إلهاءات.",
    whoWeAreText6:
      "فقط أداء ذكي وسريع مدعوم بالذكاء الاصطناعي، مع دعم الأعمال وأدوات التطوير للموزعين والمهنيين في الصناعة.",
    // Vision component translations
    visionTitle: "رؤيتنا",
    visionText: "أن نصبح أكثر",
    visionTrusted: "موثوقية",
    visionUserFriendly: "سهولة في الاستخدام",
    visionFutureReady: "جاهزية للمستقبل",
    visionTextEnd: "منصة في العالم.",
    visionTrustedLabel: "موثوق",
    visionUserFriendlyLabel: "سهل الاستخدام",
    visionFutureReadyLabel: "جاهز للمستقبل",
    // Mission component translations
    missionTitle: "مهمتنا",
    missionText1: "تزويد المستخدمين بتجربة بث",
    missionText1Highlight: "سلسة ومبتكرة",
    missionText1End: "ومتطورة",
    missionText2: "تزويد الموزعين",
    missionText2Highlight: "بمنصة إدارة فعالة",
    missionText2End: "ودعم النمو",
    // Values component translations
    valuesTitle: "قيمنا",
    valuesSubtitle: "المبادئ التي توجه كل ما نقوم به",
    valuesSimplicity: "البساطة",
    valuesSimplicityDesc: "تصميم نظيف وبديهي يمكن لأي شخص استخدامه",
    valuesTrust: "الثقة",
    valuesTrustDesc: "منصة موثوقة وآمنة يمكنك الاعتماد عليها",
    valuesInnovation: "الابتكار",
    valuesInnovationDesc: "تقنية ذكاء اصطناعي متطورة للمستقبل",
    valuesComfort: "الراحة",
    valuesComfortDesc: "تجربة سلسة مصممة لراحتك",
    valuesTransparency: "الشفافية",
    valuesTransparencyDesc: "منفتحون وصادقون في كل ما نقوم به",
    valuesSupport: "الدعم",
    valuesSupportDesc:
      "مساعدة على مدار الساعة طوال أيام الأسبوع كلما احتجت إلينا",
    // Features component translations
    featuresTitle: "ميزات المشغل",
    featuresSubtitle: "كل ما تحتاجه لتجربة بث مثالية",
    featuresModernDesign: "تصميم حديث ونظيف",
    featuresModernDesignDesc: "واجهة خفيفة ومريحة للعين تضع المحتوى في المقدمة",
    featuresInstantAccess: "وصول فوري",
    featuresInstantAccessDesc: "ادخل الخادم وابدأ المشاهدة فوراً",
    featuresSecureStable: "آمن ومستقر",
    featuresSecureStableDesc: "مبني لأقصى أداء وحماية وسرعة",
    featuresInteractiveIntelligence: "ذكاء تفاعلي",
    featuresInteractiveIntelligenceDesc:
      "يتعلم من استخدامك ليقترح أفضل المحتوى المدعوم بالذكاء الاصطناعي",
    featuresSmartSearch: "محرك بحث ذكي",
    featuresSmartSearchDesc: "اكتشاف محتوى سريع وبديهي وذكي",
    // HowItWorks component translations
    howItWorksTitle: "كيف يعمل",
    howItWorksSubtitle: "ابدأ في 3 خطوات بسيطة فقط",
    howItWorksStep1Title: "تحميل وتثبيت",
    howItWorksStep1Desc: "ابحث عن سيرفو بلاير في متجر جهازك وقم بتثبيته.",
    howItWorksStep1Note: "متاح حالياً على سامسونج وإل جي",
    howItWorksStep1ComingSoon:
      "قريباً على أندرويد تي في، آي أو إس، توكو، ويندوز، وآبل تي في",
    howItWorksStep2Title: "أدخل بيانات الاعتماد",
    howItWorksStep2Desc: "أدخل رابط الخادم أو رمز التفعيل عبر الموقع.",
    howItWorksStep3Title: "استمتع بالبث",
    howItWorksStep3Desc: "دع ذكاءنا الاصطناعي يحسن تجربتك واستمتع ببث سلس.",
    howItWorksAvailablePlatforms: "المنصات المتاحة",
    howItWorksComingSoon: "قريباً",
    // WhyChooseUs component translations
    whyChooseUsTitle: "لماذا تختار أن تصبح موزعاً معنا",
    whyChooseUsSubtitle: "إشترك مع سيرفو اليوم وإحصل على تجربة البث المستقبلية",
    whyChooseUsFullControl: "تحكم كامل",
    whyChooseUsFullControlDesc: "تحكم كامل في عملائك من خلال لوحة تحكم مهنية",
    whyChooseUsSupport: "دعم فني على مدار الساعة",
    whyChooseUsSupportDesc: "مساعدة على مدار الساعة كلما احتجت إليها",
    whyChooseUsPricing: "أسعار تنافسية",
    whyChooseUsPricingDesc: "قيمة ممتازة مقابل المال مع أسعار الجملة",
    whyChooseUsOffers: "عروض حصرية",
    whyChooseUsOffersDesc: "باقات وعروض خاصة لموزعينا",
    whyChooseUsTrusted: "منصة موثوقة",
    whyChooseUsTrustedDesc:
      "منصة حديثة وموثوقة مدعومة بالذكاء الاصطناعي — محبوبة من العملاء",
    whyChooseUsManagement: "إدارة مركزية",
    whyChooseUsManagementDesc:
      "تحكم في جميع المستخدمين والأجهزة والاشتراكات في مكان واحد",
    whyChooseUsPerformance: "أداء موثوق",
    whyChooseUsPerformanceDesc:
      "وداعاً للتوقف وعدم الاستقرار — سيرفو يوفر أداءً ثابتاً وسلساً على مدار الساعة",
    whyChooseUsPartnership:
      "👉 إشترك مع سيرفو اليوم وإحصل على تجربة البث المستقبلية.",
    whyChooseUsStartPartnership: "ابدأ شراكتك",
    // Contact component translations
    contactTitle: "تواصل معنا",
    contactSubtitle:
      "لمزيد من المعلومات أو الاستفسارات التجارية، لا تتردد في التواصل معنا",
    contactGetInTouch: "تواصل معنا",
    contactEmail: "البريد الإلكتروني",
    contactSupport: "الدعم",
    contactSupportAvailable: "متاح على مدار الساعة",
    contactResponseTime: "وقت الاستجابة",
    contactResponseTimeValue: "خلال 24 ساعة",
    contactFollowUs: "تابعنا",
    contactName: "الاسم",
    contactNamePlaceholder: "اسمك",
    contactEmailPlaceholder: "بريدك@الإلكتروني.com",
    contactSubject: "الموضوع",
    contactSubjectPlaceholder: "كيف يمكننا المساعدة؟",
    contactMessage: "الرسالة",
    contactMessagePlaceholder: "رسالتك...",
    contactSendMessage: "إرسال الرسالة",
  },
};
